% NOTE: This is for calculating the Animation video for the PCA factors in a time range
%       using the output csv files generated by the PCA analysis
% HIST:  - 1o Oct, 2021: Created by Patra
%=========================================================================
function PCA_Animation=PCA_Animation(year, assettype, Assetnumber, PCAfactor)
T1=1:1:24; %Time steps
coeff1=[];
%[pathstr,name,ext] = fileparts(filename);
files = dir(strcat('Coefficients/',assettype,'_coefficient',year,'*.csv'));% read a single asset
PCA_Animation = figure;
videoname=strcat(assettype,PCAfactor,year,'.avi');
writerObj = VideoWriter(videoname); % Name it.
writerObj.FrameRate = 1; % How many frames per second.
open(writerObj);  
for k=1:size(files)
    filename=strcat('Coefficients/',files(k).name);
    Array=readtable(filename);
    a=(Assetnumber-1)*96+1;
    i=a;j=i+23;
    if contains(PCAfactor, 'coefficient1')
        coeff1=Array{i:j,1};
    elseif contains(PCAfactor, 'coefficient2')
        i=i+24;j=j+24;
        coeff1=Array{i:j,1};
    elseif contains(PCAfactor, 'coefficient3')
        i=i+48;j=j+48;
        coeff1=Array{i:j,1};
    elseif contains(PCAfactor, 'coefficient4')
        i=i+72;j=j+72;
        coeff1=Array{i:j,1};
    end
    x = T1; % Note the transpose.
    y = coeff1;
    pause(0.1);
    figure(PCA_Animation); % Makes sure you use your desired frame.
    plot(x,y,'.-b');
    frame = getframe(gcf); % 'gcf' can handle if you zoom in to take a movie.
    ylim([-0.6 0.65])
%     filenameN=files(k).name;
%     [pathstr,name,ext] = fileparts(filenameN);
%     Title=strcat(name);
%     title(Title)
    writeVideo(writerObj, frame);
end
hold off
close(writerObj); % Saves the movie.